spring:
  mail:
    host: smtp.gmail.com
    port: 465
    username: ilyazovorozali08@gmail.com
    password: lbyanzfxphmogwsw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
    test-connection: false
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
  sql:
    init:
      data-locations: classpath:templates/data_init.sql
      mode: always
  application:
    name: hakaton
  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    driver-class-name: org.postgresql.Driver
#    username: postgres
#    password: Orozali2003
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''

jwt:
  secret-key: 66556A586E3272357538782F4125442A472D4B6150645367566B597033733676