apiVersion: apps/v1
kind: Deployment
metadata:
  name: hakaton-deployment
  labels:
    app: hakaton
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hakaton
  template:
    metadata:
      labels:
        app: hakaton
    spec:
      containers:
        - name: hakaton
          image: "adpsorcerer/hakaton:s13"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hakaton
spec:
  selector:
    app: hakaton
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
